version: '3.7'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: sua_senha_wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    user: www-data
    image: wordpress:php8.3-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: sua_senha_wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./php/php.ini-development:/usr/local/etc/php/php.ini
      # - ./php/phpinfo.php:/var/www/html/phpinfo.php
    depends_on:
      - db

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/http
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - wordpress

volumes:
  db_data:
  wordpress_data: