version: 0.2
#env:
#  secrets-manager:
#    REACT_APP_MY_VAR: /ECS-CLUSTER/cluster-testecs:REACT_APP_MY_VAR
phases:
  install:
    commands:
      - "ls -a"
  build:
    commands:
      - export STAGE=$STAGE
      - mkdir app
#      - cat $CODEBUILD_SRC_DIR_source_output
      - cp -r $CODEBUILD_SRC_DIR_source_output ./app
      - rm -rf .env || true

      - echo "buildspec"
#      - cd ./app/01
#      - ls
#      - yarn install
#      - yarn build
      - cp ./Terraform/aws/code_deploy/config/appspec.yml ./appspec.yml
#      - touch ./app/.env
#      - echo "REACT_APP_MY_VAR=$REACT_APP_MY_VAR" > ./app/.env

      

  post_build:
    commands:
      - printf '{"tag":"%s:%s"}' "$REPOSITORY_URI" "$IMAGE_TAG" > /tmp/build.json
artifacts:
  files:
    - /tmp/build.json
  discard-paths: yes