version: 0.0
os: linux
files:
  - source: /
    destination: /
#permissions:
#  - object: /
#    pattern: "**"
#    owner: ec2-user
#    group: ec2-user
hooks:
  BeforeInstall:
    - location: ./Terraform/aws/code_deploy/scripts/my_before_install.sh
      runas: ec2-user
  ApplicationStart:
    - location: ./Terraform/aws/code_deploy/scripts/my_start_server.sh
      runas: ec2-user